### ISSUE TITLE
Occasional "bursts"

### ISSUE THREAD

**Issue by dkadrios** [robertsonics/WAV-Trigger-Arduino-Serial-Library#13]
I've a strange issue that I've not been able to track down info on.  When taxing the board with a lot of quickly played tracks (with trackPlayPoly, no locks) every few minutes or so the WT will play a more or less random track at full volume.  I say "more or less" because it seems to choose these from a limited pool of tracks; that is, I hear the same 10 or so out of the 4096 I have on the card.
 
Other than that there seems to be no rhyme or reason behind it.  The tracks that this happens on are not ones that were being played at the time (I placed debug msgs in the library calls to confirm), and it will happen during both periods of heavy playing, but then will also happen when resuming from rest.  It's quite weird.

I'm using the latest firmware, but this also was happening with the previous version as well.

I'm driving the WT from a Pro Mirco, using AltSoftSerial on pin 5 to tx.  Powering it from 9V 800ma.  Only connections made on the WT are power and rx.

**Comment by robertsonics** [comment]
My first thought is that you might be sending more serial data than the WAV Trigger can keep up with. Serial data bytes are received under a high priority interrupt and placed into a circular buffer, which is then processed in the foreground at a lower priority than playing audio. This buffer is 256 bytes long, so that if you send a lot of serial commands faster than they can be processed, the buffer will fill up and you'll start losing bytes. It's possible that truncated messages could be misinterpreted.

Can you throttle back the rate at which you're sending messages and see if this helps?

**Comment by dkadrios** [comment]
Is that buffer in the firmware?  I'm using AltSoftSerial so I presume the data is being capped at 57600 baud.  The data is being generated via MIDI so I would assume that further caps it at lower at 31250.
The events are human generated (drum triggers) and are not procedural, so I would further presume they are no where close to hitting that limit, barring any super-human speed :)
I will go ahead though and try to limit the speed.  The only way I can think of how to do that at the moment is to use a timer to control when I'm reading incoming MIDI events.  What would you say is the theoretical limit to how quickly the WT can accept commands?

**Comment by robertsonics** [comment]
Yes, the receive buffer is in implemented in firmware. Keep in mind that the WAV Trigger serial protocol messages have many more bytes per message than a typical MIDI message. The Control Track command is 8 bytes, whereas a MIDI Note-On is only 3 and sometimes 2 bytes. If you slam the WAV Trigger with 32+ 8-byte messages at full baud rate, it won't keep up and you will lose bytes.

**Comment by dkadrios** [comment]
Thanks for your help.  Introducing about 3ms of latency into the flow seems to have done the trick, with no perceptible delay.
