### ISSUE TITLE
Off-Topic: I wrote a python library fro the WavTrigger

### ISSUE THREAD

**Issue by wayoda** [robertsonics/WAV-Trigger-Arduino-Serial-Library#2]
Sorry for coming in through the backdoor but I couldn't find any other contact information on you site.

I wrote a python library for the WavTrigger 
> https://github.com/wayoda/rswt

Documentation is here: 
> http://wayoda.github.io/rswt/

The library is also on PyPI : 
> https://pypi.python.org/pypi/rswt

There is also a issue with the list of playing tracks returned by the `WavTrigger` :
> https://github.com/wayoda/rswt/issues

Eberhard

**Comment by robertsonics** [comment]
Hi Eberhard,

Thanks for the email! This is great. Do you mind if I post a link to it?

I'll fix the returned track numbers in the next release.

-Jamie

**Comment by wayoda** [comment]
Hi Jamie
> Do you mind if I post a link to it?

No, that was the main reason for posting this issue. I thought the python-lib might be useful for others too.

> I'll fix the returned track numbers in the next release.

Thanks, I will keep my code as it is and put big disclaimer in the docs.

Eberhard
