### ISSUE TITLE
URL Links are broken since the robertsonics website revamp

### ISSUE THREAD

**Issue by KieranReck** [robertsonics/WAV-Trigger-Arduino-Serial-Library#27]
Hi there, hopefully a simple one seen as it isn't related to any code. Since the RobertSonics website was revamped, none of the URLs in the GitHub point anywhere, they all go to the 404 page (eg http://robertsonics.com/2015/04/25/arduino-serial-control-tutorial/)

**Comment by robertsonics** [comment]
Thanks for the heads-up. Will try to get this repaired ASAP. In the meantime, the articles are still available on the new site under "Articles"

**Comment by cafelizardo** [comment]
Yes I noticed the broken links last night as well and was going to comment but then I found the articles.  Lots of good info in there.

**Comment by KieranReck** [comment]
> Thanks for the heads-up. Will try to get this repaired ASAP. In the meantime, the articles are still available on the new site under "Articles"

Thanks for that! I did manage to find them but I didn't think of looking before reporting the issue, my bad!

**Comment by robertsonics** [comment]
No, I'm glad you did report it, thanks. Should be fixed now.

**Comment by KieranReck** [comment]
Awesome, that has fixed it. Also, loving the new website :)
