### ISSUE TITLE
trackFade() doesn't play nicely with looping.

### ISSUE THREAD

**Issue by tshead** [robertsonics/WAV-Trigger-Arduino-Serial-Library#3]
I've been experimenting with variations on the following code and running into problems with trackFade().  The symptoms are:

* Playback of looping track begins.
* After two seconds, the track begins to fade.
* But before the fade completes, the track jumps back to full volume, and continues playing forever.

Same symptoms if I reduce the fade time to 1000 ms.  If I reduce it to 500ms, I don't hear any fade at all.  Not sure if this overlaps with #1, but maybe there's some sort of race condition happening if the loop occurs during the fade?

Cheers,
Tim

```
#include <AltSoftSerial.h>
#include <wavTrigger.h>

wavTrigger audio;

#define BELL 100

void setup()
{
  Serial.begin(9600);
  
  audio.start();
  audio.stopAllTracks();
  audio.masterGain(-10); // For my sanity
  delay(2000);
  
  audio.trackLoop(BELL, true);
  audio.trackGain(BELL, 0);
  audio.trackPlayPoly(BELL);
  delay(2000);
  audio.trackFade(BELL, -40, 2000, true);
}

void loop()
{  
}
```

**Comment by tshead** [comment]
I should add that controlling the track gain myself works fine in the short run.

**Comment by robertsonics** [comment]
Hi Tim,

Thanks for the detailed email. Sadly, I've been aware of this behavior 
for a while now. The issue is that currently, the track gain is reset 
each time the track is started, and since looping is really just 
restarting the track, that's what you're observing. I really need to 
preserve the fade parameters when the track is "looped". But with a long 
list of desired features and enhancements, it's often the squeaky wheel 
that gets the attention.

I was hoping to be able to support true, seamless looping - that's what 
I've been working on this weekend. But I'm running short on memory with 
this CPU, so real looping may have to wait for the next hardware 
version. In the meantime, I'll see if there's something I can do to 
address this behavior.

I know it's not what you want to hear, but you can always loop and 
extend the file in your wav editor to make it so that the track never 
actually restarts - microSD card space is typically not an issue.

-Jamie
> Timothy M. Shead <mailto:notifications@github.com>
> July 18, 2015 at 11:48 AM
>
> I've been experimenting with variations on the following code and 
> running into problems with trackFade(). The symptoms are:
>
>   * Playback of looping track begins.
>   * After two seconds, the track begins to fade.
>   * But before the fade completes, the track jumps back to full
>     volume, and continues playing forever.
>
> Same symptoms if I reduce the fade time to 1000 ms. If I reduce it to 
> 500ms, I don't hear any fade at all. Not sure if this overlaps with #1 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/1>, 
> but maybe there's some sort of race condition happening if the loop 
> occurs during the fade?
>
> Cheers,
> Tim
>
> |#include <AltSoftSerial.h>
> #include <wavTrigger.h>
>
> wavTrigger audio;
>
> #define BELL 100
>
> void setup()
> {
> Serial.begin(9600);
>
> audio.start();
> audio.stopAllTracks();
> audio.masterGain(-10); // For my sanity
> delay(2000);
>
> audio.trackLoop(BELL, true);
> audio.trackGain(BELL, 0);
> audio.trackPlayPoly(BELL);
> delay(2000);
> audio.trackFade(BELL, -40, 2000, true);
> }
>
> void loop()
> {
> }
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/3>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by robertsonics** [comment]
Hi Tim,

If you're adventurous, you can try the attached firmware v1.22. It's 
intended to fix the fading-while-looping issue, but I haven't been able 
to set up to test myself. Will do so tomorrow.

-Jamie

> Timothy M. Shead <mailto:notifications@github.com>
> July 18, 2015 at 11:48 AM
>
> I've been experimenting with variations on the following code and 
> running into problems with trackFade(). The symptoms are:
>
>   * Playback of looping track begins.
>   * After two seconds, the track begins to fade.
>   * But before the fade completes, the track jumps back to full
>     volume, and continues playing forever.
>
> Same symptoms if I reduce the fade time to 1000 ms. If I reduce it to 
> 500ms, I don't hear any fade at all. Not sure if this overlaps with #1 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/1>, 
> but maybe there's some sort of race condition happening if the loop 
> occurs during the fade?
>
> Cheers,
> Tim
>
> |#include <AltSoftSerial.h>
> #include <wavTrigger.h>
>
> wavTrigger audio;
>
> #define BELL 100
>
> void setup()
> {
> Serial.begin(9600);
>
> audio.start();
> audio.stopAllTracks();
> audio.masterGain(-10); // For my sanity
> delay(2000);
>
> audio.trackLoop(BELL, true);
> audio.trackGain(BELL, 0);
> audio.trackPlayPoly(BELL);
> delay(2000);
> audio.trackFade(BELL, -40, 2000, true);
> }
>
> void loop()
> {
> }
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/3>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by tshead** [comment]
Definitely anxious to give it a shot, but not sure where to look for attachment?

Cheers,
Tim

**Comment by robertsonics** [comment]
Sorry if no attachment. Out until later. Will check when I get home and resend.

**Comment by robertsonics** [comment]
Email I sent definitely had an attachment. So does this one. Perhaps 
your email service doesn't like .zip or .hex files?

I'll post it on my website after I get a chance to test myself.

-Jamie

> Timothy M. Shead <mailto:notifications@github.com>
> July 18, 2015 at 6:13 PM
>
> Definitely anxious to give it a shot, but not sure where to look for 
> attachment?
>
> Cheers,
> Tim
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/3#issuecomment-122609943>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by tshead** [comment]
Thanks for trying - when I look at the message source, it's being delivered from a github.com email server - it wouldn't surprise me to hear that github is stripping-out attachments.  Live and learn.  I'll be happy to test it as soon as it's live.

Many thanks,
Tim

**Comment by robertsonics** [comment]
Hi Tim,

Just posted firmware v1.22 to the WAV Trigger Downloads page on my 
website. Let me know if it works for you now.

http://robertsonics.com/wav-trigger-downloads/

-Jamie
> Timothy M. Shead <mailto:notifications@github.com>
> July 19, 2015 at 8:05 AM
>
> Thanks for trying - when I look at the message source, it's being 
> delivered from a github.com email server - it wouldn't surprise me to 
> hear that github is stripping-out attachments. Live and learn. I'll be 
> happy to test it as soon as it's live.
>
> Many thanks,
> Tim
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/3#issuecomment-122670477>.
>
> Timothy M. Shead <mailto:notifications@github.com>
> July 18, 2015 at 11:48 AM
>
> I've been experimenting with variations on the following code and 
> running into problems with trackFade(). The symptoms are:
>
>   * Playback of looping track begins.
>   * After two seconds, the track begins to fade.
>   * But before the fade completes, the track jumps back to full
>     volume, and continues playing forever.
>
> Same symptoms if I reduce the fade time to 1000 ms. If I reduce it to 
> 500ms, I don't hear any fade at all. Not sure if this overlaps with #1 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/1>, 
> but maybe there's some sort of race condition happening if the loop 
> occurs during the fade?
>
> Cheers,
> Tim
>
> |#include <AltSoftSerial.h>
> #include <wavTrigger.h>
>
> wavTrigger audio;
>
> #define BELL 100
>
> void setup()
> {
> Serial.begin(9600);
>
> audio.start();
> audio.stopAllTracks();
> audio.masterGain(-10); // For my sanity
> delay(2000);
>
> audio.trackLoop(BELL, true);
> audio.trackGain(BELL, 0);
> audio.trackPlayPoly(BELL);
> delay(2000);
> audio.trackFade(BELL, -40, 2000, true);
> }
>
> void loop()
> {
> }
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/3>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by tshead** [comment]
That's working like  a charm, thanks for the quick turnaround!

Cheers,
Tim
