### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Gremy150** [robertsonics/WAV-Trigger-Arduino-Serial-Library#5]
Hi there! 
So I'm a High School student and this year, we have a special project to do in Engineering Science. Basically we are replicating a drum set electronically. 
From here I started out with a basic MP3 Shield, to allow my arduino uno chip to play music. But I needed heavier hardware. That's why I'm using the Wav Trigger Shield. 

So I downloaded the Library from here and launched the example to get into the heart of the subject. 
As indicated in the example and here I downloaded the other 2 library's, necessary for the program. 

But I compiled before a transfer to my controller chip and then this came up: 

   Arduino : 1.6.1 (Windows 7), Card : "Arduino Uno"

   In file included from WTriggerUno.ino:38:0:

   C:\Program Files (x86)\Arduino\librarys\WAV-Trigger-Arduino-Serial-Library master/wavTrigger.h:59:44: fatal error: ../AltSoftSerial/AltSoftSerial.h: No such file or directory

    #include "../AltSoftSerial/AltSoftSerial.h"
   
                                               ^
   
   compilation terminated.

Error during compilation.

To me it look's like there is something missing in the files, something not included. 
I re-downloaded the library's but the same thing happened every time.
So if you could tell me what I missed it would help a lot. 
Thanks!

**Comment by robertsonics** [comment]
The example requires the AltSoftSerial library be installed as well. 
Please review this tutorial with the relevant links:

http://robertsonics.com/2015/04/25/arduino-serial-control-tutorial/

> Gremy150 <mailto:notifications@github.com>
> February 15, 2016 at 7:36 AM
>
> Hi there!
> So I'm a High School student and this year, we have a special project 
> to do in Engineering Science. Basically we are replicating a drum set 
> electronically.
> From here I started out with a basic MP3 Shield, to allow my arduino 
> uno chip to play music. But I needed heavier hardware. That's why I'm 
> using the Wav Trigger Shield.
>
> So I downloaded the Library from here and launched the example to get 
> into the heart of the subject.
> As indicated in the example and here I downloaded the other 2 
> library's, necessary for the program.
>
> But I compiled before a transfer to my controller chip and then this 
> came up:
>
> Arduino : 1.6.1 (Windows 7), Card : "Arduino Uno"
>
> In file included from WTriggerUno.ino:38:0:
>
> C:\Program Files 
> (x86)\Arduino\librarys\WAV-Trigger-Arduino-Serial-Library 
> master/wavTrigger.h:59:44: fatal error: 
> ../AltSoftSerial/AltSoftSerial.h: No such file or directory
>
> |#include "../AltSoftSerial/AltSoftSerial.h"
>
> ^
> |
>
> compilation terminated.
>
> Erreur during compilation.
>
> To me it look's like there is something missing in the files, 
> something not included.
> I re-downloaded the library's but the same thing happened every time.
> So if you could tell me what I missed it would help a lot.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robertsonics/WAV-Trigger-Arduino-Serial-Library/issues/5>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by Gremy150** [comment]
Thank you very much for the link, it helped a lot ! 
Sorry for answering late, I had very violent exams in the meantime.
