### ISSUE TITLE
Skipping sound coming from wav trigger

### ISSUE THREAD

**Issue by hwestbrook** [robertsonics/WAV-Trigger-Arduino-Serial-Library#9]
Hi Robert, 

Wasn't sure where to leave you this issue, so I've filed it here.

I've got a wav trigger with the following version:
57415620547269676765722076312E323820202000000

Once in a while my WAV trigger will make this sound: [LINK](http://vocaroo.com/i/s03KOWLO5F3Z). Other times it will make the sound it is supposed to play. 

Do you know what might be causing this? 

I am using the WAV trigger in conjunction with an external amp. The sound is being triggered over serial connection.

**Comment by robertsonics** [comment]
Never heard anything like that before. I would confirm that it happens with headphones (not connected to external amp) and if so, contact SparkFun for support. You could simply have a bad unit.

**Comment by hwestbrook** [comment]
Hi Robert, 

Thanks for the response. I have a number of these, and they were all experiencing the same issue. 

The root cause had to do with a bad power supply setup. Initially they were getting sufficient power, but after a few seconds the input power was dropping to a level below the WAV trigger's requirements. 

They are work fine now that I've fixed this. 

Heath

PS, is there a good way to contact you? I'd like to discuss using the WAV trigger in a commercial project.

**Comment by robertsonics** [comment]
info(at)robertsonics(dot)com
